// Generated by gencpp from file serial_com/detect.msg
// DO NOT EDIT!


#ifndef SERIAL_COM_MESSAGE_DETECT_H
#define SERIAL_COM_MESSAGE_DETECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_com
{
template <class ContainerAllocator>
struct detect_
{
  typedef detect_<ContainerAllocator> Type;

  detect_()
    : pitch(0.0)
    , yaw(0.0)
    , command(0)
    , extend(0)  {
    }
  detect_(const ContainerAllocator& _alloc)
    : pitch(0.0)
    , yaw(0.0)
    , command(0)
    , extend(0)  {
  (void)_alloc;
    }



   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef int16_t _command_type;
  _command_type command;

   typedef int16_t _extend_type;
  _extend_type extend;





  typedef boost::shared_ptr< ::serial_com::detect_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_com::detect_<ContainerAllocator> const> ConstPtr;

}; // struct detect_

typedef ::serial_com::detect_<std::allocator<void> > detect;

typedef boost::shared_ptr< ::serial_com::detect > detectPtr;
typedef boost::shared_ptr< ::serial_com::detect const> detectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_com::detect_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_com::detect_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace serial_com

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'serial_com': ['/home/bili/Autoaim-master/src/serial_com/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::serial_com::detect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_com::detect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_com::detect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_com::detect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_com::detect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_com::detect_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_com::detect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "48ec59d707cdeaf1adf035a4f071355f";
  }

  static const char* value(const ::serial_com::detect_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x48ec59d707cdeaf1ULL;
  static const uint64_t static_value2 = 0xadf035a4f071355fULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_com::detect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_com/detect";
  }

  static const char* value(const ::serial_com::detect_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_com::detect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pitch\n"
"float32 yaw \n"
"int16 command\n"
"int16 extend\n"
;
  }

  static const char* value(const ::serial_com::detect_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_com::detect_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.command);
      stream.next(m.extend);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct detect_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_com::detect_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_com::detect_<ContainerAllocator>& v)
  {
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "command: ";
    Printer<int16_t>::stream(s, indent + "  ", v.command);
    s << indent << "extend: ";
    Printer<int16_t>::stream(s, indent + "  ", v.extend);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_COM_MESSAGE_DETECT_H
